/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '1.25' }],
        sm: ['14px', { lineHeight: '1.5' }],
        base: ['16px', { lineHeight: '1.5' }],
        lg: ['18px', { lineHeight: '1.5' }],
        xl: ['20px', { lineHeight: '1.5' }],
        '2xl': ['24px', { lineHeight: '1.5' }],
        '3xl': ['32px', { lineHeight: '1.25' }],
        '4xl': ['40px', { lineHeight: '1.25' }],
      },
      fontWeight: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        loose: '1.75',
      },
      colors: {
        primary: '#2563EB',
        primary_hover: '#1E40AF',
        secondary: '#6B7280',
        surface_light: '#FFFFFF',
        surface_dark: '#1F2937',
        bg_light: '#F8FAFC',
        bg_dark: '#111827',
        danger: '#DC2626',
        success: '#16A34A',
        warning: '#F59E0B',
        info: '#0284C7',
        muted: '#6B7280',
        text_light: '#111827',
        text_dark: '#F9FAFB',
        border: '#E6E9EE',
      },
      borderRadius: {
        sm: '6px',
        md: '12px',
        lg: '20px',
        pill: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(2,6,23,0.06)',
        md: '0 6px 18px rgba(2,6,23,0.08)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
        slow: '400ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.4,0,0.2,1)',
        soft: 'cubic-bezier(0.2,0.9,0.2,1)',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        'content-max': '1200px',
      },
    },
  },
  plugins: [],
}